import 'fake-indexeddb/auto';import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {putArt,getArt,listArt,pendingArt,artKey} from '../dist/storage.mjs';
import {handleArt} from '../netlify/functions/_shared/art-handler.mjs';
import {initFamily,family,flush,mergeGallery,loadRemote,pairFamily} from '../dist/sync.mjs';
class Store{constructor(){this.data=new Map();this.counter=0}async getWithMetadata(k){return this.data.get(k)||null}async list({prefix}){return {blobs:[...this.data.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key}))}}async setJSON(k,data,o){const old=this.data.get(k);if((o.onlyIfNew&&old)||(o.onlyIfMatch&&old?.etag!==o.onlyIfMatch))return {modified:false};const etag=String(++this.counter);this.data.set(k,{data,etag});return {modified:true,etag}}}
const local=new Map(),store=new Store();let offline=false,status='',fork;
globalThis.crypto??=webcrypto;globalThis.localStorage={getItem:k=>local.get(k),setItem:(k,v)=>local.set(k,v)};globalThis.document={cookie:''};globalThis.location={protocol:'https:'};globalThis.window={addEventListener(){}};Object.defineProperty(globalThis,'navigator',{configurable:true,value:{onLine:true}});globalThis.fetch=async(url,options)=>{if(offline)throw new Error('offline');return handleArt(new Request('https://club.example'+url,options),store)};
function record(id,profile='Olivia'){return {id,key:artKey(family,profile,id),family,profile,title:'A masterpiece',pageId:'garden',paint:'data:image/png;base64,AA==',thumbnail:'data:image/webp;base64,AA==',customBase:null,updatedAt:1,revision:crypto.randomUUID(),pending:true,etag:null}}
test('local offline saves, per-child separation, cross-device pull, conflict copies, pairing',async()=>{await initFamily(s=>status=s,(id,a)=>fork=a);assert.equal(family.length,64);const original=record('offline-art-id');await putArt(original);assert.equal((await listArt(family,'Olivia')).length,1);assert.equal((await listArt(family,'Henry')).length,0);offline=true;await flush();assert.equal((await pendingArt(family)).length,1);assert.equal(status,'waiting');offline=false;await flush();assert.equal((await pendingArt(family)).length,0);const synced=await getArt(original.key);assert.ok(synced.etag);const {art:remote}=await (await fetch(`/api/art?profile=Olivia&id=${original.id}`,{headers:{Authorization:'Bearer '+family}})).json();assert.equal(remote.title,original.title);
// Another device saves using the cloud revision; this local device still has the old revision.
await fetch(`/api/art?profile=Olivia&id=${original.id}`,{method:'PUT',headers:{Authorization:'Bearer '+family},body:JSON.stringify({art:{...remote,title:'Other device version',revision:'other'},etag:synced.etag})});await putArt({...synced,title:'This device version',revision:'local-new',pending:true});await flush();assert.ok(fork);assert.match(fork.title,/another version/);assert.equal((await getArt(original.key)).title,'Other device version');assert.equal((await getArt(fork.key)).title,'This device version · another version');await new Promise(resolve=>setTimeout(resolve,1100));await flush();assert.equal((await pendingArt(family)).length,0);const gallery=await mergeGallery('Olivia');assert.equal(gallery.length,2);
const otherFamily='f'.repeat(64);await pairFamily(otherFamily);assert.equal((await listArt(family,'Olivia')).length,0);assert.equal((await mergeGallery('Olivia')).length,0);assert.equal(local.get('little_color_family'),otherFamily);});
