import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import vm from 'node:vm';import {webcrypto} from 'node:crypto';import * as core from '../dist/core.mjs';import * as library from '../dist/library.mjs';import * as drag from '../dist/puzzle-drag.mjs';
// Exercises the actual app controller with mocked DOM/canvas/storage. This does not test rendering.
class Element{
 constructor(tag='div'){Object.assign(this,{tag,children:[],attributes:{},dataset:{},hidden:false,disabled:false,open:false,value:'',textContent:'',className:'',style:{setProperty(k,v){this[k]=v}}});this.classList={contains:c=>this.className.split(' ').includes(c),toggle:(c,on)=>{const s=new Set(this.className.split(' ').filter(Boolean));on??=!s.has(c);on?s.add(c):s.delete(c);this.className=[...s].join(' ')},add:c=>this.classList.toggle(c,true),remove:c=>this.classList.toggle(c,false)}}
 setAttribute(k,v){this.attributes[k]=String(v);if(k==='id')this.id=v;if(k==='class')this.className=v;if(k.startsWith('data-'))this.dataset[k.slice(5)]=String(v)}getAttribute(k){return this.attributes[k]}
 append(...els){for(const e of els){if(e.parentElement)e.remove();e.parentElement=this;this.children.push(e)}}replaceChildren(...els){this.children=[];this.append(...els)}remove(){this.parentElement.children=this.parentElement.children.filter(e=>e!==this)}querySelectorAll(s){return walk(this).filter(e=>matches(e,s))}querySelector(s){return this.querySelectorAll(s)[0]}focus(){this.ownerDocument.activeElement=this}showModal(){this.open=true}close(){this.open=false}
 getContext(){return this.context??={globalCompositeOperation:'source-over',operations:[],fillRect(){},clearRect(){},drawImage(){},beginPath(){},moveTo(){},lineTo(){},stroke(){this.operations.push(this.globalCompositeOperation)},getImageData(){return {data:new Uint8ClampedArray(core.SIDE*core.SIDE*4).fill(255)}},putImageData(){}}}toDataURL(type='image/png'){return `data:${type};base64,AA==`}getBoundingClientRect(){return {left:0,top:0,width:900,height:900}}setPointerCapture(){}
}
function walk(e){return e.children.flatMap(c=>[c,...walk(c)])}
function matches(e,s){if(s.includes(' ')){const [p,...tail]=s.split(' ');let a=e.parentElement;while(a){if(matches(a,p)&&matches(e,tail.join(' ')))return true;a=a.parentElement}return false}if(s[0]==='#')return e.id===s.slice(1);if(s[0]==='.')return e.classList.contains(s.slice(1));if(s[0]==='['){const [,k,v]=s.match(/^\[([^=\]]+)(?:="([^"\]]+)")?\]$/);return e.dataset[k.slice(5)]!==undefined&&(v===undefined||String(e.dataset[k.slice(5)])===v)}return e.tag===s}
async function setup(options={}){
 const html=await fs.readFile(new URL('../dist/index.html',import.meta.url),'utf8'),root=new Element('document'),ids=new Map(),stack=[root];
 for(const [full,tag,attrs] of html.matchAll(/<\/?([a-z][\w-]*)([^>]*)>/gi)){if(full.startsWith('</')){while(stack.length>1){if(stack.pop().tag===tag)break}continue}const e=new Element(tag);for(const a of attrs.matchAll(/([\w-]+)(?:="([^"]*)")?/g)){e.setAttribute(a[1],a[2]??'');if(a[1]==='hidden')e.hidden=true;if(a[1]==='disabled')e.disabled=true;if(a[1]==='value')e.value=a[2]}stack.at(-1).append(e);if(e.id)ids.set(e.id,e);if(!full.endsWith('/>')&&!['meta','link','img','input','br'].includes(tag))stack.push(e)}
 const listeners={},document={body:walk(root).find(e=>e.tag==='body'),hidden:false,getElementById:id=>ids.get(id),createElement:tag=>{const e=new Element(tag);e.ownerDocument=document;return e},createElementNS:(_,tag)=>document.createElement(tag),querySelectorAll:s=>root.querySelectorAll(s),querySelector:s=>root.querySelector(s),addEventListener:(n,cb)=>listeners[n]=cb};walk(root).forEach(e=>e.ownerDocument=document);
 let now=0;const saved=new Map(),settings=new Map();const context=vm.createContext({...core,...library,...drag,bindPuzzleDrag:(piece,options)=>drag.bindPuzzleDrag(piece,{...options,document}),PuzzleClock:class extends core.PuzzleClock{constructor(){super(()=>now)}},document,window:{addEventListener(){}},navigator:{onLine:false},location:{href:'https://club.example/'},Image:class{width=900;height=900;async decode(){if(options.decode)await options.decode();if(options.failDecode)throw new Error("decode failed")}},crypto:webcrypto,URL,Blob,Uint8ClampedArray,setTimeout(){return 1},clearTimeout(){},setInterval(){},family:'a'.repeat(64),familyPassphrase:'purple-dog-kite',ensureFamilyPassphrase:async()=> 'purple-dog-kite',getSetting:async k=>settings.get(k),setSetting:async(k,v)=>settings.set(k,v),listArt:async(f,p)=>[...saved.values()].filter(a=>a.family===f&&a.profile===p&&!a.deleted).sort((a,b)=>b.updatedAt-a.updatedAt),deleteArt:async a=>saved.set(a.key,{...a,deleted:true}),syncProblems:async()=>[],previousFamilyPhrase:async()=>'',retrySync:async()=>{},putArt:async a=>{if(options.failSave)throw new Error("storage full");saved.set(a.key,structuredClone(a));return a},getArt:async k=>saved.get(k),artKey:(f,p,id)=>f+':'+p+':'+id,initFamily:async()=>{},pairFamily:async()=>{},flush:async()=>{},mergeGallery:async p=>[...saved.values()].filter(a=>a.profile===p&&!a.deleted),loadRemote:async()=>{}});
 vm.runInContext((await fs.readFile(new URL('../dist/app.mjs',import.meta.url),'utf8')).replace(/^import[\s\S]*?;\n/gm,''),context);await new Promise(r=>setImmediate(r));
 return {document,saved,listeners,$:id=>ids.get(id),run:s=>vm.runInContext(s,context),advance:ms=>now+=ms,async click(e){assert.ok(e&&!e.disabled,'available control');await e.onclick();await new Promise(r=>setImmediate(r))}};
}
test('color → Done → Puzzle → pause → completion → personal gallery',async()=>{
 const u=await setup();await u.click(u.document.querySelector('[data-profile="Olivia"]'));assert.equal(u.document.body.dataset.view,'library');assert.equal(u.$('themes').children.length,8);await u.click(u.$('pageLibrary').children[0]);assert.equal(u.document.body.dataset.view,'studio');
 await u.click(u.$('brushTool'));u.$('canvas').onpointerdown({clientX:100,clientY:100,pointerId:1,preventDefault(){}});u.$('canvas').onpointerup();await u.click(u.$('save'));assert.equal(u.$('finishedDialog').open,true);assert.equal(u.saved.size,1);assert.equal([...u.saved.values()][0].profile,'Olivia');
 await u.click(u.$('finishedPuzzle'));assert.equal(u.$('puzzleSetup').open,true);assert.deepEqual(u.$('puzzleSizes').children.map(b=>b.getAttribute('aria-label')),['9 piece puzzle','16 piece puzzle','24 piece puzzle','36 piece puzzle']);await u.click(u.$('puzzleSizes').children[0]);assert.equal(u.run('clock.running'),false);
 await u.click(u.$('tray').children[0]);assert.equal(u.run('clock.running'),true);u.advance(2100);await u.click(u.$('pauseTimer'));assert.equal(u.$('pauseOverlay').hidden,false);const elapsed=u.run('clock.elapsed');u.advance(60000);assert.equal(u.run('clock.elapsed'),elapsed);await u.click(u.$('resume'));
 for(let i=0;i<9;i++){await u.click(u.document.querySelector(`[data-piece="${i}"]`));await u.click(u.$('board').children[i])}assert.equal(u.$('completeDialog').open,true);assert.equal(u.run('clock.complete'),true);assert.equal(u.run('clock.running'),false);const end=u.run('clock.elapsed');u.advance(10000);assert.equal(u.run('clock.elapsed'),end);await u.click(u.$('completeGallery'));assert.equal(u.document.body.dataset.view,'gallery');assert.equal(u.$('galleryItems').children.length,1);
 await u.click(u.$('switchBtn'));await u.click(u.document.querySelector('[data-profile="Henry"]'));await u.click(u.$('galleryTab'));assert.equal(u.$('galleryItems').children[0].className,'empty');
});
test('eraser uses paint layer; picking a color exits eraser; reset can be cancelled and undone',async()=>{
 const u=await setup();await u.click(u.document.querySelector('[data-profile="Issa"]'));await u.click(u.$('pageLibrary').children[0]);await u.click(u.$('eraserTool'));u.$('canvas').onpointerdown({clientX:50,clientY:50,pointerId:1,preventDefault(){}});u.$('canvas').onpointerup();assert.deepEqual(Array.from(u.run('paintCtx.operations')),['destination-out']);assert.equal(u.run('baseCtx.operations.length'),0);await u.click(u.$('palette').children[2]);assert.equal(u.run('tool'),'fill');
 await u.click(u.$('studioMore'));await u.click(u.$('clear'));const n=u.run('undo.length');await u.click(u.$('cancelReset'));assert.equal(u.run('undo.length'),n);await u.click(u.$('clear'));await u.click(u.$('confirmReset'));assert.equal(u.run('undo.length'),n+1);await u.click(u.$('undo'));assert.equal(u.$('redo').disabled,false);
});
test('36-piece puzzle has hint and restart protection; file settings require a selected player',async()=>{
 const u=await setup();await u.click(u.$('parentBtn'));assert.equal(u.$('upload').disabled,true);assert.equal(u.$('importArt').disabled,true);await u.click(u.$('closeParent'));await u.click(u.document.querySelector('[data-profile="Henry"]'));await u.click(u.$('pageLibrary').children[0]);await u.click(u.$('studioMore'));await u.click(u.$('makePuzzle'));await u.click(u.$('puzzleSizes').children[3]);assert.equal(u.$('board').children.length,36);assert.equal(u.$('tray').children.length,36);assert.equal(u.$('board').parentElement.style['--board-min'],'358px');
 await u.click(u.$('hint'));assert.equal(u.$('reference').hidden,false);await u.click(u.$('tray').children[0]);u.advance(1000);await u.click(u.$('shuffle'));assert.equal(u.$('resetDialog').open,true);await u.click(u.$('cancelReset'));assert.equal(u.run('clock.running'),true);await u.click(u.$('back'));assert.equal(u.run('clock.running'),false);
});

test('failed saves keep the child on their picture and allow a successful retry',async()=>{
 const options={failSave:true},u=await setup(options);await u.click(u.document.querySelector('[data-profile="Olivia"]'));await u.click(u.$('pageLibrary').children[0]);await u.click(u.$('save'));assert.equal(u.document.body.dataset.view,'studio');assert.equal(u.$('finishedDialog').open,false);assert.equal(u.$('save').disabled,false);assert.equal(u.run('dirty'),true);options.failSave=false;await u.click(u.$('save'));assert.equal(u.$('finishedDialog').open,true);assert.equal(u.saved.size,1);
});
test('Back cancels a slow picture load; failed image decode returns safely to the library',async()=>{
 let resolve;const wait=new Promise(r=>resolve=r),u=await setup({decode:()=>wait});await u.click(u.document.querySelector('[data-profile="Henry"]'));const opening=u.click(u.$('pageLibrary').children[0]);await new Promise(r=>setImmediate(r));assert.equal(u.$('fillTool').disabled,true);assert.equal(u.$('loadingArt').hidden,false);await u.click(u.$('backLibrary'));resolve();await opening;assert.equal(u.document.body.dataset.view,'library');assert.equal(u.run('ready'),false);
 const failed=await setup({failDecode:true});await failed.click(failed.document.querySelector('[data-profile="Henry"]'));await failed.click(failed.$('pageLibrary').children[0]);assert.equal(failed.document.body.dataset.view,'library');assert.equal(failed.run('ready'),false);
});
test('keyboard navigation restores focus; wrong puzzle placement preserves the selected piece',async()=>{
 const u=await setup();u.listeners.keydown({key:'Tab'});await u.click(u.document.querySelector('[data-profile="Issa"]'));assert.equal(u.document.activeElement,u.$('libraryHeading'));await u.click(u.$('pageLibrary').children[0]);assert.equal(u.document.activeElement,u.$('studio'));await u.click(u.$('studioMore'));await u.click(u.$('makePuzzle'));await u.click(u.$('puzzleSizes').children[0]);const piece=u.document.querySelector('[data-piece="0"]');await u.click(piece);await u.click(u.$('board').children[1]);assert.equal(u.run('selected'),0);assert.equal(u.$('tray').children.length,9);await u.click(u.$('board').children[0]);assert.equal(u.$('tray').children.length,8);assert.equal(u.document.activeElement,u.$('tray').children[0]);
});

test('upward touch drag places a piece; horizontal swiping and wrong drops keep pieces',async()=>{
 const u=await setup();await u.click(u.document.querySelector('[data-profile="Olivia"]'));await u.click(u.$('pageLibrary').children[0]);await u.click(u.$('studioMore'));await u.click(u.$('makePuzzle'));await u.click(u.$('puzzleSizes').children[0]);
 const e=(x,y)=>({pointerId:2,pointerType:'touch',isPrimary:true,clientX:x,clientY:y,preventDefault(){}});let p=u.document.querySelector('[data-piece="0"]');
 p.onpointerdown(e(100,1000));p.onpointermove(e(170,1002));p.onpointerup(e(170,1002));assert.equal(u.run('clock.running'),false);assert.equal(u.$('tray').children.length,9);
 p.onpointerdown(e(100,1000));p.onpointermove(e(100,100));assert.equal(u.run('clock.running'),true);assert.equal(u.document.querySelectorAll('.drag-ghost').length,1);p.onpointerup(e(100,100));assert.equal(u.$('tray').children.length,8);assert.equal(u.$('board').children[0].disabled,true);assert.equal(u.document.querySelectorAll('.drag-ghost').length,0);
 p=u.document.querySelector('[data-piece="1"]');p.onpointerdown(e(200,1000));p.onpointermove(e(100,400));p.onpointerup(e(100,400));assert.equal(u.$('tray').children.length,8);assert.equal(u.run('selected'),1);
 p.onpointerdown(e(200,1000));p.onpointermove(e(400,100));p.onpointercancel(e(400,100));assert.equal(u.$('tray').children.length,8);assert.equal(u.document.querySelectorAll('.drag-ghost').length,0);
});
test('the grown-up dialog shows the three-word phrase rather than the internal family key',async()=>{
 const u=await setup();await u.click(u.$('parentBtn'));await u.click(u.$('showCode'));assert.equal(u.$('familyCodeArea').hidden,false);assert.equal(u.$('familyCode').value,'purple-dog-kite');
});

test('pausing cancels an active drag and a later drag still works after resume',async()=>{
 const u=await setup();await u.click(u.document.querySelector('[data-profile="Henry"]'));await u.click(u.$('pageLibrary').children[0]);await u.click(u.$('studioMore'));await u.click(u.$('makePuzzle'));await u.click(u.$('puzzleSizes').children[0]);const p=u.document.querySelector('[data-piece="0"]'),e=(x,y)=>({pointerId:3,pointerType:'mouse',button:0,clientX:x,clientY:y,preventDefault(){}});
 p.onpointerdown(e(100,1000));p.onpointermove(e(100,100));u.advance(1000);await u.click(u.$('pauseTimer'));assert.equal(u.document.querySelectorAll('.drag-ghost').length,0);p.onpointerup(e(100,100));assert.equal(u.$('tray').children.length,9);await u.click(u.$('resume'));
 p.onpointerdown(e(100,1000));p.onpointermove(e(100,100));p.onpointerup(e(100,100));assert.equal(u.$('tray').children.length,8);
});

test('intermediate brush size and extra/custom colors stay visible on the main palette',async()=>{
 const u=await setup();await u.click(u.document.querySelector('[data-profile="Henry"]'));await u.click(u.$('pageLibrary').children[0]);
 await u.click(u.$('brushTool'));await u.click(u.$('brushSize'));assert.equal(u.run('brushSize'),52);
 await u.click(u.$('studioMore'));await u.click(u.$('extraPalette').children[10]);assert.equal(u.$('recentColor').hidden,false);
 assert.equal(u.$('recentColor').dataset.color,'#624032');assert.equal(u.$('recentColor').getAttribute('aria-pressed'),'true');assert.equal(u.$('recentColor').parentElement,u.$('palette'));
 u.$('customColor').oninput({target:{value:'#123456'}});assert.equal(u.$('recentColor').dataset.color,'#123456');
});
test('revisiting a saved page offers Continue/New; parent gallery rename and deletion work',async()=>{
 const u=await setup();await u.click(u.document.querySelector('[data-profile="Olivia"]'));await u.click(u.$('pageLibrary').children[0]);await u.click(u.$('save'));await u.click(u.$('finishedGallery'));
 await u.click(u.$('libraryTab'));await u.click(u.$('pageLibrary').children[0]);assert.equal(u.$('resumeDialog').open,true);
 await u.click(u.$('resumeSaved'));assert.equal(u.saved.size,1);
 await u.click(u.$('parentBtn'));await u.click(u.$('manageGallery'));let manage=u.$('galleryItems').children[0].children[2];await u.click(manage.children[0]);u.$('galleryTitle').value='Olivia’s cat';await u.click(u.$('saveRename'));assert.equal([...u.saved.values()][0].title,'Olivia’s cat');
 manage=u.$('galleryItems').children[0].children[2];await u.click(manage.children[1]);await u.click(u.$('confirmDelete'));assert.equal([...u.saved.values()][0].deleted,true);assert.equal(u.$('galleryItems').children[0].className,'empty');
});
